# Generated by Django 4.0.1 on 2022-04-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessman_details',
            name='image',
        ),
        migrations.RemoveField(
            model_name='businessman_details',
            name='user_name',
        ),
        migrations.AddField(
            model_name='businessman_details',
            name='adhar_card',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='businessman_details',
            name='email',
            field=models.EmailField(default='-', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessman_details',
            name='account_holder_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='businessman_details',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='businessman_details',
            name='bank_account_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='businessman_details',
            name='gst_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='businessman_details',
            name='ifsc_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='businessman_details',
            name='pan_card',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
