# Generated by Django 4.0.1 on 2022-06-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_product_details_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_details',
            name='current_price',
        ),
    ]
