# Generated by Django 4.0.3 on 2022-06-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_product_details_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100, null=True),
        ),
    ]
